### ISSUE TITLE
From Host and To host registers ??

### ISSUE THREAD

**Issue by santhoshvlsi** [skordal/potato#2]
What is the utilities of From Host and To host registers in potato core.

**Comment by skordal** [comment]
Hi,

The FROMHOST and TOHOST registers are currently only used in the testbenches, where the TOHOST register is written to when a test ends to signal to the testbench what the result of the test was.

**Comment by santhoshvlsi** [comment]
From the dump and hex files, i noticed that that TOHOST register can generate the value as one. 
what is the purpose and useage of these registers in core. can you explain more on these.

**Comment by skordal** [comment]
Yes, in all the test applications, the TOHOST register is set to 1 to indicate a successful test or used to determine which test failed if not. This is used when running the tests automatically in order for the testbench to terminate.

This is the only use of these registers in the Potato processor. Since the FROMHOST/TOHOST functionality is a nonstandard extension to the RISC-V specification, and the implementation of the registers and their functionality in the Potato processor most likely is not compatible with other implementations, it is not recommended to use these registers when writing applications for the processor.
